import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';

// Step 3: Implement Thunk Action Creator
// This function handles the asynchronous logic automatically.
export const fetchUser = createAsyncThunk('user/fetchUser', async () => {
  const response = await fetch('https://jsonplaceholder.typicode.com/users/1');
  
  if (!response.ok) {
    throw new Error('Failed to fetch user data');
  }
  
  const data = await response.json();
  return data;
});

// Step 2: Define Redux Slice for User Data
const userSlice = createSlice({
  name: 'user',
  initialState: {
    data: null,    // Holds user information
    loading: false, // Tracks loading status
    error: null,   // Holds error messages
  },
  reducers: {
    // Standard synchronous reducers can go here
  },
  extraReducers: (builder) => {
    // Handle the lifecycle actions generated by fetchUser
    builder
      .addCase(fetchUser.pending, (state) => {
        state.loading = true;
        state.error = null;
      })
      .addCase(fetchUser.fulfilled, (state, action) => {
        state.loading = false;
        state.data = action.payload; // Store the fetched user data
      })
      .addCase(fetchUser.rejected, (state, action) => {
        state.loading = false;
        state.error = action.error.message;
      });
  },
});

export default userSlice.reducer;